# Place this file in the root directory of your project
# OPEN_API_KEY and OPEN_API_BASE must be configured in PATH

dark-mode: true
auto-commits: false
show-model-warnings: false
model: openai/gemini-2.5-pro-preview-06-05

